from __future__ import annotations

from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
ADDON_TEXT = (ROOT / "addon.py").read_text(encoding="utf-8")


def test_addon_defines_runtime_service_classes() -> None:
    for name in [
        "class SceneObservationService",
        "class ViewportScreenshotService",
        "class SceneIntelligenceService",
        "class VerificationArtifactService",
        "class SceneEditService",
        "class MaterialAuthoringService",
        "class ModifierService",
        "class CollectionOrganizationService",
        "class VerifiedEditBatchService",
        "class WorkspaceSafetyDiffService",
        "class ProviderStatusService",
        "class PolyHavenService",
        "class SketchfabService",
        "class Hyper3DService",
    ]:
        assert name in ADDON_TEXT


def test_addon_initializes_runtime_service_instances() -> None:
    for name in [
        "self.scene_observation_service = SceneObservationService(self)",
        "self.viewport_screenshot_service = ViewportScreenshotService(self)",
        "self.scene_intelligence_service = SceneIntelligenceService(self)",
        "self.verification_artifact_service = VerificationArtifactService(self)",
        "self.scene_edit_service = SceneEditService(self)",
        "self.material_authoring_service = MaterialAuthoringService(self)",
        "self.modifier_service = ModifierService(self)",
        "self.collection_organization_service = CollectionOrganizationService(self)",
        "self.verified_edit_batch_service = VerifiedEditBatchService(self)",
        "self.workspace_safety_diff_service = WorkspaceSafetyDiffService(self)",
        "self.provider_status_service = ProviderStatusService(self)",
        "self.polyhaven_service = PolyHavenService(self)",
        "self.sketchfab_service = SketchfabService(self)",
        "self.hyper3d_service = Hyper3DService(self)",
    ]:
        assert name in ADDON_TEXT


def test_addon_binds_runtime_service_command_methods() -> None:
    for name in [
        "self.get_scene_info = self.scene_observation_service.get_scene_info",
        "self.get_object_info = self.scene_observation_service.get_object_info",
        "self.get_viewport_screenshot = self.viewport_screenshot_service.get_viewport_screenshot",
        "self.get_scene_index = self.scene_intelligence_service.get_scene_index",
        "self.get_object_deep_info = self.scene_intelligence_service.get_object_deep_info",
        "self.get_selection_info = self.scene_intelligence_service.get_selection_info",
        "self.get_scene_health = self.scene_intelligence_service.get_scene_health",
        "self.capture_viewport_pack = self.verification_artifact_service.capture_viewport_pack",
        "self.create_verification_snapshot = self.verification_artifact_service.create_verification_snapshot",
        "self.list_verification_snapshots = self.verification_artifact_service.list_verification_snapshots",
        "self.get_supported_edit_operations = self.scene_edit_service.get_supported_edit_operations",
        "self.create_primitive_object = self.scene_edit_service.create_primitive_object",
        "self.transform_object = self.scene_edit_service.transform_object",
        "self.duplicate_object = self.scene_edit_service.duplicate_object",
        "self.delete_objects = self.scene_edit_service.delete_objects",
        "self.set_object_visibility = self.scene_edit_service.set_object_visibility",
        "self.create_basic_material = self.material_authoring_service.create_basic_material",
        "self.assign_material = self.material_authoring_service.assign_material",
        "self.update_material_properties = self.material_authoring_service.update_material_properties",
        "self.add_object_modifier = self.modifier_service.add_object_modifier",
        "self.update_object_modifier = self.modifier_service.update_object_modifier",
        "self.remove_object_modifier = self.modifier_service.remove_object_modifier",
        "self.create_collection = self.collection_organization_service.create_collection",
        "self.move_objects_to_collection = self.collection_organization_service.move_objects_to_collection",
        "self.delete_collection = self.collection_organization_service.delete_collection",
        "self.run_verified_edit_batch = self.verified_edit_batch_service.run_verified_edit_batch",
        "self.get_task_workspace = self.workspace_safety_diff_service.get_task_workspace",
        "self.create_workspace_task = self.workspace_safety_diff_service.create_workspace_task",
        "self.update_workspace_task = self.workspace_safety_diff_service.update_workspace_task",
        "self.list_workspace_tasks = self.workspace_safety_diff_service.list_workspace_tasks",
        "self.add_workspace_todo = self.workspace_safety_diff_service.add_workspace_todo",
        "self.update_workspace_todo = self.workspace_safety_diff_service.update_workspace_todo",
        "self.list_workspace_todos = self.workspace_safety_diff_service.list_workspace_todos",
        "self.record_operation_journal_entry = self.workspace_safety_diff_service.record_operation_journal_entry",
        "self.get_operation_journal = self.workspace_safety_diff_service.get_operation_journal",
        "self.create_scene_snapshot = self.workspace_safety_diff_service.create_scene_snapshot",
        "self.list_scene_snapshots = self.workspace_safety_diff_service.list_scene_snapshots",
        "self.diff_scene_snapshots = self.workspace_safety_diff_service.diff_scene_snapshots",
        "self.detect_user_changes = self.workspace_safety_diff_service.detect_user_changes",
        "self.rollback_to_scene_snapshot = self.workspace_safety_diff_service.rollback_to_scene_snapshot",
        "self.undo_last_blender_operation = self.workspace_safety_diff_service.undo_last_blender_operation",
        "self.get_polyhaven_status = self.provider_status_service.get_polyhaven_status",
        "self.get_hyper3d_status = self.provider_status_service.get_hyper3d_status",
        "self.get_sketchfab_status = self.provider_status_service.get_sketchfab_status",
        "self.get_polyhaven_categories = self.polyhaven_service.get_polyhaven_categories",
        "self.search_polyhaven_assets = self.polyhaven_service.search_polyhaven_assets",
        "self.download_polyhaven_asset = self.polyhaven_service.download_polyhaven_asset",
        "self.set_texture = self.polyhaven_service.set_texture",
        "self.search_sketchfab_models = self.sketchfab_service.search_sketchfab_models",
        "self.download_sketchfab_model = self.sketchfab_service.download_sketchfab_model",
        "self.create_rodin_job = self.hyper3d_service.create_rodin_job",
        "self.poll_rodin_job_status = self.hyper3d_service.poll_rodin_job_status",
        "self.import_generated_asset = self.hyper3d_service.import_generated_asset",
    ]:
        assert name in ADDON_TEXT


def test_addon_runtime_services_preserve_existing_contracts() -> None:
    for name in [
        "get_scene_info",
        "get_object_info",
        "get_viewport_screenshot",
        "get_scene_index",
        "get_object_deep_info",
        "get_selection_info",
        "get_scene_health",
        "capture_viewport_pack",
        "create_verification_snapshot",
        "list_verification_snapshots",
        "get_supported_edit_operations",
        "create_primitive_object",
        "transform_object",
        "duplicate_object",
        "delete_objects",
        "set_object_visibility",
        "create_basic_material",
        "assign_material",
        "update_material_properties",
        "add_object_modifier",
        "update_object_modifier",
        "remove_object_modifier",
        "create_collection",
        "move_objects_to_collection",
        "delete_collection",
        "run_verified_edit_batch",
        "get_task_workspace",
        "create_workspace_task",
        "update_workspace_task",
        "list_workspace_tasks",
        "add_workspace_todo",
        "update_workspace_todo",
        "list_workspace_todos",
        "record_operation_journal_entry",
        "get_operation_journal",
        "create_scene_snapshot",
        "list_scene_snapshots",
        "diff_scene_snapshots",
        "detect_user_changes",
        "rollback_to_scene_snapshot",
        "undo_last_blender_operation",
        "get_polyhaven_status",
        "get_hyper3d_status",
        "get_sketchfab_status",
        "get_polyhaven_categories",
        "search_polyhaven_assets",
        "download_polyhaven_asset",
        "set_texture",
        "search_sketchfab_models",
        "download_sketchfab_model",
        "create_rodin_job",
        "poll_rodin_job_status",
        "import_generated_asset",
        "blendermcp_use_polyhaven",
        "blendermcp_use_hyper3d",
        "blendermcp_use_sketchfab",
        "execute_code",
        "complete_geometry_node",
        "get_geometry_nodes_status",
    ]:
        assert name in ADDON_TEXT
