from __future__ import annotations

from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
from tests._addon_source import ADDON_PACKAGE_SOURCE as ADDON_TEXT


def test_addon_defines_runtime_service_classes() -> None:
    for name in [
        "class SceneObservationService",
        "class ViewportScreenshotService",
        "class SceneIntelligenceService",
        "class VerificationArtifactService",
        "class SceneEditService",
        "class MaterialAuthoringService",
        "class ModifierService",
        "class SelectionIntelligenceService",
        "class VertexGroupService",
        "class ShapeKeyService",
        "class LatticeDeformationService",
        "class DeformationModifierService",
        "class DirectMeshEditService",
        "class DeformationWorkflowBatchService",
        "class MethodIntelligenceService",
        "class AssetMaterialWorkflowService",
        "class UVSelectionMeasurementService",
        "class SculptWorkflowService",
        "class CollectionOrganizationService",
        "class VerifiedEditBatchService",
        "class WorkspaceSafetyDiffService",
        "class ProviderStatusService",
        "class PolyHavenService",
        "class SketchfabService",
        "class Hyper3DService",
    ]:
        assert name in ADDON_TEXT


def test_addon_initializes_runtime_service_instances() -> None:
    for name in [
        "self.scene_observation_service = SceneObservationService(self)",
        "self.viewport_screenshot_service = ViewportScreenshotService(self)",
        "self.scene_intelligence_service = SceneIntelligenceService(self)",
        "self.verification_artifact_service = VerificationArtifactService(self)",
        "self.scene_edit_service = SceneEditService(self)",
        "self.material_authoring_service = MaterialAuthoringService(self)",
        "self.selection_intelligence_service = SelectionIntelligenceService(self)",
        "self.vertex_group_service = VertexGroupService(self)",
        "self.shape_key_service = ShapeKeyService(self)",
        "self.lattice_deformation_service = LatticeDeformationService(self)",
        "self.deformation_modifier_service = DeformationModifierService(self)",
        "self.direct_mesh_edit_service = DirectMeshEditService(self)",
        "self.deformation_workflow_batch_service = DeformationWorkflowBatchService(self)",
        "self.method_intelligence_service = MethodIntelligenceService(self)",
        "self.asset_material_workflow_service = AssetMaterialWorkflowService(self)",
        "self.uv_selection_measurement_service = UVSelectionMeasurementService(self)",
        "self.sculpt_workflow_service = SculptWorkflowService(self)",
        "self.modifier_service = ModifierService(self)",
        "self.collection_organization_service = CollectionOrganizationService(self)",
        "self.verified_edit_batch_service = VerifiedEditBatchService(self)",
        "self.workspace_safety_diff_service = WorkspaceSafetyDiffService(self)",
        "self.provider_status_service = ProviderStatusService(self)",
        "self.polyhaven_service = PolyHavenService(self)",
        "self.sketchfab_service = SketchfabService(self)",
        "self.hyper3d_service = Hyper3DService(self)",
    ]:
        assert name in ADDON_TEXT


def test_addon_binds_runtime_service_command_methods() -> None:
    for name in [
        "self.get_scene_info = self.scene_observation_service.get_scene_info",
        "self.get_object_info = self.scene_observation_service.get_object_info",
        "self.get_viewport_screenshot = self.viewport_screenshot_service.get_viewport_screenshot",
        "self.get_scene_index = self.scene_intelligence_service.get_scene_index",
        "self.get_object_deep_info = self.scene_intelligence_service.get_object_deep_info",
        "self.get_selection_info = self.scene_intelligence_service.get_selection_info",
        "self.get_scene_health = self.scene_intelligence_service.get_scene_health",
        "self.capture_viewport_pack = self.verification_artifact_service.capture_viewport_pack",
        "self.create_verification_snapshot = self.verification_artifact_service.create_verification_snapshot",
        "self.list_verification_snapshots = self.verification_artifact_service.list_verification_snapshots",
        "self.get_supported_edit_operations = self.scene_edit_service.get_supported_edit_operations",
        "self.create_primitive_object = self.scene_edit_service.create_primitive_object",
        "self.transform_object = self.scene_edit_service.transform_object",
        "self.duplicate_object = self.scene_edit_service.duplicate_object",
        "self.delete_objects = self.scene_edit_service.delete_objects",
        "self.set_object_visibility = self.scene_edit_service.set_object_visibility",
        "self.create_basic_material = self.material_authoring_service.create_basic_material",
        "self.assign_material = self.material_authoring_service.assign_material",
        "self.update_material_properties = self.material_authoring_service.update_material_properties",
        "self.get_selection_deep_info = self.selection_intelligence_service.get_selection_deep_info",
        "self.get_mesh_component_summary = self.selection_intelligence_service.get_mesh_component_summary",
        "self.create_vertex_group = self.vertex_group_service.create_vertex_group",
        "self.update_vertex_group_weights = self.vertex_group_service.update_vertex_group_weights",
        "self.list_vertex_groups = self.vertex_group_service.list_vertex_groups",
        "self.delete_vertex_groups = self.vertex_group_service.delete_vertex_groups",
        "self.create_shape_key = self.shape_key_service.create_shape_key",
        "self.update_shape_key_value = self.shape_key_service.update_shape_key_value",
        "self.edit_shape_key_offsets = self.shape_key_service.edit_shape_key_offsets",
        "self.list_shape_keys = self.shape_key_service.list_shape_keys",
        "self.delete_shape_keys = self.shape_key_service.delete_shape_keys",
        "self.create_lattice_deformer = self.lattice_deformation_service.create_lattice_deformer",
        "self.update_lattice_deformer = self.lattice_deformation_service.update_lattice_deformer",
        "self.apply_lattice_to_object = self.lattice_deformation_service.apply_lattice_to_object",
        "self.remove_lattice_deformer = self.lattice_deformation_service.remove_lattice_deformer",
        "self.add_deformation_modifier = self.deformation_modifier_service.add_deformation_modifier",
        "self.update_deformation_modifier = self.deformation_modifier_service.update_deformation_modifier",
        "self.create_region_deformation = self.deformation_workflow_batch_service.create_region_deformation",
        "self.run_deformation_workflow_batch = self.deformation_workflow_batch_service.run_deformation_workflow_batch",
        "self.get_method_plan = self.method_intelligence_service.get_method_plan",
        "self.list_operation_playbooks = self.method_intelligence_service.list_operation_playbooks",
        "self.get_tricks_knowledge_base = self.method_intelligence_service.get_tricks_knowledge_base",
        "self.get_anti_pattern_rules = self.method_intelligence_service.get_anti_pattern_rules",
        "self.get_modifier_recipes = self.method_intelligence_service.get_modifier_recipes",
        "self.score_selection_confidence = self.method_intelligence_service.score_selection_confidence",
        "self.scan_blender_asset_libraries = self.asset_material_workflow_service.scan_blender_asset_libraries",
        "self.preview_asset = self.asset_material_workflow_service.preview_asset",
        "self.import_texture_folder = self.asset_material_workflow_service.import_texture_folder",
        "self.create_style_material = self.asset_material_workflow_service.create_style_material",
        "self.create_paintable_texture = self.asset_material_workflow_service.create_paintable_texture",
        "self.delete_images = self.asset_material_workflow_service.delete_images",
        "self.list_uv_maps = self.uv_selection_measurement_service.list_uv_maps",
        "self.create_vertex_group_from_uv_island = self.uv_selection_measurement_service.create_vertex_group_from_uv_island",
        "self.measure_object = self.uv_selection_measurement_service.measure_object",
        "self.measure_distance = self.uv_selection_measurement_service.measure_distance",
        "self.create_proportional_deformation = self.uv_selection_measurement_service.create_proportional_deformation",
        "self.get_sculpt_status = self.sculpt_workflow_service.get_sculpt_status",
        "self.configure_sculpt_brush = self.sculpt_workflow_service.configure_sculpt_brush",
        "self.create_sculpt_mask_from_vertex_group = self.sculpt_workflow_service.create_sculpt_mask_from_vertex_group",
        "self.run_shape_key_sculpt_workflow = self.sculpt_workflow_service.run_shape_key_sculpt_workflow",
        "self.add_object_modifier = self.modifier_service.add_object_modifier",
        "self.update_object_modifier = self.modifier_service.update_object_modifier",
        "self.remove_object_modifier = self.modifier_service.remove_object_modifier",
        "self.create_collection = self.collection_organization_service.create_collection",
        "self.move_objects_to_collection = self.collection_organization_service.move_objects_to_collection",
        "self.delete_collection = self.collection_organization_service.delete_collection",
        "self.run_verified_edit_batch = self.verified_edit_batch_service.run_verified_edit_batch",
        "self.get_task_workspace = self.workspace_safety_diff_service.get_task_workspace",
        "self.create_workspace_task = self.workspace_safety_diff_service.create_workspace_task",
        "self.update_workspace_task = self.workspace_safety_diff_service.update_workspace_task",
        "self.list_workspace_tasks = self.workspace_safety_diff_service.list_workspace_tasks",
        "self.add_workspace_todo = self.workspace_safety_diff_service.add_workspace_todo",
        "self.update_workspace_todo = self.workspace_safety_diff_service.update_workspace_todo",
        "self.list_workspace_todos = self.workspace_safety_diff_service.list_workspace_todos",
        "self.record_operation_journal_entry = self.workspace_safety_diff_service.record_operation_journal_entry",
        "self.get_operation_journal = self.workspace_safety_diff_service.get_operation_journal",
        "self.create_scene_snapshot = self.workspace_safety_diff_service.create_scene_snapshot",
        "self.list_scene_snapshots = self.workspace_safety_diff_service.list_scene_snapshots",
        "self.diff_scene_snapshots = self.workspace_safety_diff_service.diff_scene_snapshots",
        "self.detect_user_changes = self.workspace_safety_diff_service.detect_user_changes",
        "self.rollback_to_scene_snapshot = self.workspace_safety_diff_service.rollback_to_scene_snapshot",
        "self.undo_last_blender_operation = self.workspace_safety_diff_service.undo_last_blender_operation",
        "self.get_polyhaven_status = self.provider_status_service.get_polyhaven_status",
        "self.get_hyper3d_status = self.provider_status_service.get_hyper3d_status",
        "self.get_sketchfab_status = self.provider_status_service.get_sketchfab_status",
        "self.get_polyhaven_categories = self.polyhaven_service.get_polyhaven_categories",
        "self.search_polyhaven_assets = self.polyhaven_service.search_polyhaven_assets",
        "self.download_polyhaven_asset = self.polyhaven_service.download_polyhaven_asset",
        "self.set_texture = self.polyhaven_service.set_texture",
        "self.search_sketchfab_models = self.sketchfab_service.search_sketchfab_models",
        "self.download_sketchfab_model = self.sketchfab_service.download_sketchfab_model",
        "self.create_rodin_job = self.hyper3d_service.create_rodin_job",
        "self.poll_rodin_job_status = self.hyper3d_service.poll_rodin_job_status",
        "self.import_generated_asset = self.hyper3d_service.import_generated_asset",
    ]:
        assert name in ADDON_TEXT


def test_addon_runtime_services_preserve_existing_contracts() -> None:
    for name in [
        "get_scene_info",
        "get_object_info",
        "get_viewport_screenshot",
        "get_scene_index",
        "get_object_deep_info",
        "get_selection_info",
        "get_scene_health",
        "capture_viewport_pack",
        "create_verification_snapshot",
        "list_verification_snapshots",
        "get_supported_edit_operations",
        "create_primitive_object",
        "transform_object",
        "duplicate_object",
        "delete_objects",
        "set_object_visibility",
        "create_basic_material",
        "assign_material",
        "update_material_properties",
        "add_object_modifier",
        "update_object_modifier",
        "remove_object_modifier",
        "create_collection",
        "move_objects_to_collection",
        "delete_collection",
        "run_verified_edit_batch",
        "get_task_workspace",
        "create_workspace_task",
        "update_workspace_task",
        "list_workspace_tasks",
        "add_workspace_todo",
        "update_workspace_todo",
        "list_workspace_todos",
        "record_operation_journal_entry",
        "get_operation_journal",
        "create_scene_snapshot",
        "list_scene_snapshots",
        "diff_scene_snapshots",
        "detect_user_changes",
        "rollback_to_scene_snapshot",
        "undo_last_blender_operation",
        "get_polyhaven_status",
        "get_hyper3d_status",
        "get_sketchfab_status",
        "get_polyhaven_categories",
        "search_polyhaven_assets",
        "download_polyhaven_asset",
        "set_texture",
        "search_sketchfab_models",
        "download_sketchfab_model",
        "create_rodin_job",
        "poll_rodin_job_status",
        "import_generated_asset",
        "blendermcp_use_polyhaven",
        "blendermcp_use_hyper3d",
        "blendermcp_use_sketchfab",
        "execute_code",
        "complete_geometry_node",
        "get_geometry_nodes_status",
    ]:
        assert name in ADDON_TEXT
